---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/kubespy version
    register: kubespy_test_output
  - debug:
      msg: '{{ kubespy_test_output.stdout }}'
