---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install at {{ kubespy_install_dir }}
  become: true
  stat:
    path: '{{ kubespy_install_dir }}'
  changed_when: false
  register: kubespy_binary
- when: not kubespy_binary.stat.exists
  block:
    - name: downloading {{ kubespy_url }}...
      become: true
      become_user: root
      get_url:
        url: '{{ kubespy_url }}'
        dest: '{{ kubespy_tmp_tgz }}'
        mode: 0644
    - name: mkdir {{ kubespy_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ kubespy_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchiving {{ kubespy_tmp_tgz }} into {{ kubespy_install_dir }}...
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ kubespy_tmp_tgz }}'
        dest: '{{ kubespy_install_dir }}'
        creates: '{{ kubespy_exe }}'
  always:
    - name: cleanup {{ kubespy_tmp_tgz }}
      become: true
      become_user: root
      file:
        path: '{{ kubespy_tmp_tgz }}'
        state: absent
- name: linking {{ kubespy_link }} to {{ kubespy_exe }}...
  become: true
  become_user: root
  file:
    src: '{{ kubespy_exe }}'
    dest: '{{ kubespy_link }}'
    state: link
